/**
 * CTL/EXP da BOSS GX-10: o que cada pé/botão faz e as 20 atribuições (assigns).
 *
 * Deslocamentos:
 *   · por memória  -> [MemoryCommon], dentro da memória (temporária ou de usuário)
 *   · do sistema   -> [SystemControl], endereço 00 00 10 00
 * Os nomes das linhas seguem o que aparece na tela da pedaleira (GX-10); o manual
 * chama de BankDown/BankUp, Manual Num1/2, CNum, Ctl1-3, Exp1Sw, Exp1 e Exp2.
 */
window.GX10_CTLEXP_VERSAO = "0.11.2";
window.GX10_CTLEXP = {
 "listas": {
  "funcNum": [
   "OFF",
   "NUM 1",
   "DOWN",
   "UP",
   "BPM TAP",
   "TUNER",
   "MEMORY/MAN",
   "TUNER/MAN",
   "MAN/TUNER",
   "AMP CTL 1",
   "AMP CTL 2",
   "WAH",
   "DIV CH.SEL",
   "SEND/RETURN",
   "LOOP CTL",
   "LOOPER STOP",
   "LOOPER CLEAR",
   "MIDI START"
  ],
  "funcCNum": [
   "OFF",
   "BPM TAP",
   "TUNER",
   "MEMORY/MAN",
   "TUNER/MAN",
   "MAN/TUNER",
   "AMP CTL 1",
   "AMP CTL 2",
   "WAH",
   "DIV CH.SEL",
   "SEND/RETURN",
   "LOOP CTL",
   "LOOPER STOP",
   "LOOPER CLEAR",
   "MIDI START"
  ],
  "funcCtl": [
   "OFF",
   "BANK ▼",
   "BANK ▲",
   "DOWN",
   "UP",
   "BPM TAP",
   "TUNER",
   "MEMORY/MAN",
   "TUNER/MAN",
   "MAN/TUNER",
   "AMP CTL 1",
   "AMP CTL 2",
   "WAH",
   "DIV CH.SEL",
   "SEND/RETURN",
   "LOOP CTL",
   "LOOPER STOP",
   "LOOPER CLEAR",
   "MIDI START"
  ],
  "funcExp": [
   "OFF",
   "FOOT VOL",
   "WAH",
   "FV/WAH",
   "FV+TU",
   "FV+TU/WAH"
  ],
  "modo": [
   "TOGGLE",
   "MOMENT"
  ],
  "preferencia": [
   "MEMORY",
   "SYSTEM"
  ],
  "comModo": [
   "AMP CTL 1",
   "AMP CTL 2",
   "WAH",
   "DIV CH.SEL",
   "SEND/RETURN"
  ]
 },
 "controles": [
  {
   "rotulo": "▼ (down)",
   "lista": "funcNum",
   "modo": false,
   "mem": {
    "funcao": 20,
    "modo": 38
   },
   "sis": {
    "pref": 4,
    "funcao": 22,
    "modo": 40
   }
  },
  {
   "rotulo": "▲ (up)",
   "lista": "funcNum",
   "modo": false,
   "mem": {
    "funcao": 21,
    "modo": 39
   },
   "sis": {
    "pref": 5,
    "funcao": 23,
    "modo": 41
   }
  },
  {
   "rotulo": "MANUAL ▼",
   "lista": "funcCNum",
   "modo": false,
   "mem": {
    "funcao": 23,
    "modo": 41
   },
   "sis": {
    "pref": 7,
    "funcao": 25,
    "modo": 43
   }
  },
  {
   "rotulo": "MANUAL ▲",
   "lista": "funcCNum",
   "modo": false,
   "mem": {
    "funcao": 24,
    "modo": 42
   },
   "sis": {
    "pref": 8,
    "funcao": 26,
    "modo": 44
   }
  },
  {
   "rotulo": "CURNUM",
   "lista": "funcCNum",
   "modo": false,
   "mem": {
    "funcao": 22,
    "modo": 40
   },
   "sis": {
    "pref": 6,
    "funcao": 24,
    "modo": 42
   }
  },
  {
   "rotulo": "CTL1",
   "lista": "funcCtl",
   "modo": true,
   "mem": {
    "funcao": 27,
    "modo": 45
   },
   "sis": {
    "pref": 11,
    "funcao": 29,
    "modo": 47
   }
  },
  {
   "rotulo": "CTL2",
   "lista": "funcCtl",
   "modo": true,
   "mem": {
    "funcao": 28,
    "modo": 46
   },
   "sis": {
    "pref": 12,
    "funcao": 30,
    "modo": 48
   }
  },
  {
   "rotulo": "CTL3",
   "lista": "funcCtl",
   "modo": true,
   "mem": {
    "funcao": 29,
    "modo": 47
   },
   "sis": {
    "pref": 13,
    "funcao": 31,
    "modo": 49
   }
  },
  {
   "rotulo": "EXP1 SW",
   "lista": "funcCtl",
   "modo": true,
   "mem": {
    "funcao": 31,
    "modo": 49
   },
   "sis": {
    "pref": 15,
    "funcao": 33,
    "modo": 51
   }
  },
  {
   "rotulo": "EXP1 PEDAL",
   "lista": "funcExp",
   "modo": false,
   "mem": {
    "funcao": 32,
    "modo": null
   },
   "sis": {
    "pref": 16,
    "funcao": 34,
    "modo": null
   }
  },
  {
   "rotulo": "EXP2",
   "lista": "funcExp",
   "modo": false,
   "mem": {
    "funcao": 33,
    "modo": null
   },
   "sis": {
    "pref": 17,
    "funcao": 35,
    "modo": null
   }
  }
 ],
 "assign": {
  "campos": [
   {
    "chave": "sw",
    "rotulo": "On/Off",
    "desloc": 0,
    "tipo": "byte",
    "lista": [
     "OFF",
     "ON"
    ]
   },
   {
    "chave": "fxItem",
    "rotulo": "Block",
    "desloc": 1,
    "tipo": "byte",
    "min": 0,
    "max": 19,
    "base1": true
   },
   {
    "chave": "target",
    "rotulo": "Target",
    "desloc": 2,
    "tipo": "nibbles4",
    "min": 0,
    "max": 740,
    "alvos": true
   },
   {
    "chave": "targetMin",
    "rotulo": "Target min",
    "desloc": 6,
    "tipo": "nibbles4",
    "min": 0,
    "max": 65535
   },
   {
    "chave": "targetMax",
    "rotulo": "Target max",
    "desloc": 10,
    "tipo": "nibbles4",
    "min": 0,
    "max": 65535
   },
   {
    "chave": "source",
    "rotulo": "Source",
    "desloc": 14,
    "tipo": "byte",
    "lista": [
     "NUM 1",
     "NUM 2",
     "NUM 3",
     "NUM 4",
     "MAN 1",
     "MAN 2",
     "MAN 3",
     "MAN 4",
     "CUR NUM",
     "BANK DOWN",
     "BANK UP",
     "CTL 1",
     "CTL 2",
     "CTL 3",
     "CTL 4",
     "EXP 1 SW",
     "EXP 1",
     "EXP 2",
     "INT PDL",
     "WAVE PDL",
     "INPUT",
     "CC# 1",
     "CC# 2",
     "CC# 3",
     "CC# 4",
     "CC# 5",
     "CC# 6",
     "CC# 7",
     "CC# 8",
     "CC# 9",
     "CC# 10",
     "CC# 11",
     "CC# 12",
     "CC# 13",
     "CC# 14",
     "CC# 15",
     "CC# 16",
     "CC# 17",
     "CC# 18",
     "CC# 19",
     "CC# 20",
     "CC# 21",
     "CC# 22",
     "CC# 23",
     "CC# 24",
     "CC# 25",
     "CC# 26",
     "CC# 27",
     "CC# 28",
     "CC# 29",
     "CC# 30",
     "CC# 31",
     "CC# 64",
     "CC# 65",
     "CC# 66",
     "CC# 67",
     "CC# 68",
     "CC# 69",
     "CC# 70",
     "CC# 71",
     "CC# 72",
     "CC# 73",
     "CC# 74",
     "CC# 75",
     "CC# 76",
     "CC# 77",
     "CC# 78",
     "CC# 79",
     "CC# 80",
     "CC# 81",
     "CC# 82",
     "CC# 83",
     "CC# 84",
     "CC# 85",
     "CC# 86",
     "CC# 87",
     "CC# 88",
     "CC# 89",
     "CC# 90",
     "CC# 91",
     "CC# 92",
     "CC# 93",
     "CC# 94",
     "CC# 95"
    ]
   },
   {
    "chave": "mode",
    "rotulo": "Mode",
    "desloc": 15,
    "tipo": "byte",
    "lista": [
     "TOGGLE",
     "MOMENT"
    ]
   },
   {
    "chave": "waveRate",
    "rotulo": "Wave rate",
    "desloc": 16,
    "tipo": "byte",
    "min": 0,
    "max": 118
   },
   {
    "chave": "waveform",
    "rotulo": "Waveform",
    "desloc": 17,
    "tipo": "byte",
    "lista": [
     "SAW",
     "TRI",
     "SINE"
    ]
   },
   {
    "chave": "intTrigger",
    "rotulo": "Int pedal trigger",
    "desloc": 18,
    "tipo": "byte",
    "lista": [
     "MEM CHANGE",
     "NUM 1",
     "NUM 2",
     "NUM 3",
     "NUM 4",
     "MAN 1",
     "MAN 2",
     "MAN 3",
     "MAN 4",
     "CUR NUM",
     "BANK DOWN",
     "BANK UP",
     "CTL 1",
     "CTL 2",
     "CTL 3",
     "CTL 4",
     "EXP 1 SW",
     "EXP 1 PDL-LO",
     "EXP 1 PDL-MID",
     "EXP 1 PDL-HI",
     "EXP 2",
     "CC# 1",
     "CC# 2",
     "CC# 3",
     "CC# 4",
     "CC# 5",
     "CC# 6",
     "CC# 7",
     "CC# 8",
     "CC# 9",
     "CC# 10",
     "CC# 11",
     "CC# 12",
     "CC# 13",
     "CC# 14",
     "CC# 15",
     "CC# 16",
     "CC# 17",
     "CC# 18",
     "CC# 19",
     "CC# 20",
     "CC# 21",
     "CC# 22",
     "CC# 23",
     "CC# 24",
     "CC# 25",
     "CC# 26",
     "CC# 27",
     "CC# 28",
     "CC# 29",
     "CC# 30",
     "CC# 31",
     "CC# 64",
     "CC# 65",
     "CC# 66",
     "CC# 67",
     "CC# 68",
     "CC# 69",
     "CC# 70",
     "CC# 71",
     "CC# 72",
     "CC# 73",
     "CC# 74",
     "CC# 75",
     "CC# 76",
     "CC# 77",
     "CC# 78",
     "CC# 79",
     "CC# 80",
     "CC# 81",
     "CC# 82",
     "CC# 83",
     "CC# 84",
     "CC# 85",
     "CC# 86",
     "CC# 87",
     "CC# 88",
     "CC# 89",
     "CC# 90",
     "CC# 91",
     "CC# 92",
     "CC# 93",
     "CC# 94",
     "CC# 95"
    ]
   },
   {
    "chave": "intTime",
    "rotulo": "Int pedal time",
    "desloc": 19,
    "tipo": "byte",
    "min": 0,
    "max": 100
   },
   {
    "chave": "intCurve",
    "rotulo": "Int pedal curve",
    "desloc": 20,
    "tipo": "byte",
    "lista": [
     "LINEAR",
     "SLOW RISE",
     "FAST RISE"
    ]
   },
   {
    "chave": "actLo",
    "rotulo": "Act range lo",
    "desloc": 21,
    "tipo": "nibbles4",
    "min": 0,
    "max": 16382
   },
   {
    "chave": "actHi",
    "rotulo": "Act range hi",
    "desloc": 25,
    "tipo": "nibbles4",
    "min": 1,
    "max": 16383
   },
   {
    "chave": "midiCh",
    "rotulo": "MIDI channel",
    "desloc": 29,
    "tipo": "byte",
    "lista": [
     "SYSTEM",
     "1",
     "2",
     "3",
     "4",
     "5",
     "6",
     "7",
     "8",
     "9",
     "10",
     "11",
     "12",
     "13",
     "14",
     "15",
     "16"
    ]
   },
   {
    "chave": "midiCc",
    "rotulo": "MIDI CC#",
    "desloc": 30,
    "tipo": "byte",
    "min": 0,
    "max": 127
   },
   {
    "chave": "ccMin",
    "rotulo": "CC value min",
    "desloc": 31,
    "tipo": "nibbles4",
    "min": 0,
    "max": 16383
   },
   {
    "chave": "ccMax",
    "rotulo": "CC value max",
    "desloc": 35,
    "tipo": "nibbles4",
    "min": 0,
    "max": 16383
   },
   {
    "chave": "midiPc",
    "rotulo": "MIDI PC#",
    "desloc": 40,
    "tipo": "byte",
    "min": 0,
    "max": 127,
    "base1": true
   }
  ],
  "total": 20,
  "passo": 64,
  "desloc1": 256,
  "alvos": [
   "— none —",
   "EFFECT(RENAMED WITH TYPE): ON/OFF",
   "AC GUITAR SIM: BODY",
   "AC GUITAR SIM: LOW",
   "AC GUITAR SIM: HIGH",
   "AC GUITAR SIM: LEVEL",
   "AC RESONANCE: TYPE",
   "AC RESONANCE: RESONANCE",
   "AC RESONANCE: TONE",
   "AC RESONANCE: LEVEL",
   "SLOW GEAR: SENS",
   "SLOW GEAR: RISE TIME",
   "SLOW GEAR: LEVEL",
   "BASS SLOW GEAR: SENS",
   "BASS SLOW GEAR: RISE TIME",
   "BASS SLOW GEAR: LEVEL",
   "DEFRETTER: SENS",
   "DEFRETTER: DEPTH",
   "DEFRETTER: TONE",
   "DEFRETTER: EFFECT LEVEL",
   "DEFRETTER: ATTACK",
   "DEFRETTER: RESONANCE",
   "DEFRETTER: DIRECT MIX",
   "BASS DEFRETTER: SENS",
   "BASS DEFRETTER: ATTACK",
   "BASS DEFRETTER: TONE",
   "BASS DEFRETTER: EFFECT LEVEL",
   "BASS DEFRETTER: DIRECT MIX",
   "WAH: WAH TYPE",
   "WAH: PEDAL POSITION",
   "WAH: PEDAL MIN",
   "WAH: PEDAL MAX",
   "WAH: EFFECT LEVEL",
   "WAH: DIRECT MIX",
   "BASS WAH: PEDAL POS",
   "BASS WAH: PEDAL MIN",
   "BASS WAH: PEDAL MAX",
   "BASS WAH: EFFECT LEVEL",
   "BASS WAH: DIRECT MIX",
   "TOUCH WAH: FILTER MODE",
   "TOUCH WAH: POLARITY",
   "TOUCH WAH: SENS",
   "TOUCH WAH: FREQUENCY",
   "TOUCH WAH: RESONANCE",
   "TOUCH WAH: DECAY",
   "TOUCH WAH: EFFECT LEVEL",
   "TOUCH WAH: DIRECT MIX",
   "BASS TOUCH WAH: FILTER MODE",
   "BASS TOUCH WAH: POLARITY",
   "BASS TOUCH WAH: SENS",
   "BASS TOUCH WAH: FREQUENCY",
   "BASS TOUCH WAH: RESONANCE",
   "BASS TOUCH WAH: DECAY",
   "BASS TOUCH WAH: EFFECT LEVEL",
   "BASS TOUCH WAH: DIRECT MIX",
   "COMPRESSOR: TYPE",
   "COMPRESSOR: SUSTAIN",
   "COMPRESSOR: ATTACK",
   "COMPRESSOR: LEVEL",
   "COMPRESSOR: TONE",
   "COMPRESSOR: DIRECT MIX",
   "X COMP: ATTACK",
   "X COMP: LEVEL",
   "X COMP: TONE",
   "X COMP: RATIO",
   "X COMP: DIRECT MIX",
   "X COMP: SUSTAIN",
   "BASS X COMP: ATTACK",
   "BASS X COMP: LEVEL",
   "BASS X COMP: TONE",
   "BASS X COMP: RATIO",
   "BASS X COMP: DIRECT MIX",
   "BASS X COMP: THRESHOLD",
   "BOOSTER: TYPE",
   "BOOSTER: BOOST",
   "BOOSTER: TONE",
   "BOOSTER: EFFECT LEVEL",
   "BOOSTER: BOTTOM",
   "BOOSTER: DIRECT MIX",
   "BOOSTER: SOLO SW",
   "BOOSTER: SOLO LEVEL",
   "OVERDRIVE: TYPE",
   "OVERDRIVE: DRIVE",
   "OVERDRIVE: TONE",
   "OVERDRIVE: EFFECT LEVEL",
   "OVERDRIVE: BOTTOM",
   "OVERDRIVE: DIRECT MIX",
   "OVERDRIVE: SOLO SW",
   "OVERDRIVE: SOLO LEVEL",
   "BASS OVERDRIVE: DRIVE",
   "BASS OVERDRIVE: TONE",
   "BASS OVERDRIVE: EFFECT LEVEL",
   "BASS OVERDRIVE: BOTTOM",
   "BASS OVERDRIVE: DIRECT MIX",
   "BASS OVERDRIVE: SOLO SW",
   "BASS OVERDRIVE: SOLO LEVEL",
   "X OVERDRIVE: DRIVE",
   "X OVERDRIVE: TONE",
   "X OVERDRIVE: EFFECT LEVEL",
   "X OVERDRIVE: BOTTOM",
   "X OVERDRIVE: DIRECT MIX",
   "X OVERDRIVE: SOLO SW",
   "X OVERDRIVE: SOLO LEVEL",
   "X BASS OVERDRIVE: DRIVE",
   "X BASS OVERDRIVE: TONE",
   "X BASS OVERDRIVE: EFFECT LEVEL",
   "X BASS OVERDRIVE: BOTTOM",
   "X BASS OVERDRIVE: DIRECT MIX",
   "X BASS OVERDRIVE: SOLO SW",
   "X BASS OVERDRIVE: SOLO LEVEL",
   "X DISTORTION: DRIVE",
   "X DISTORTION: TONE",
   "X DISTORTION: EFFECT LEVEL",
   "X DISTORTION: BOTTOM",
   "X DISTORTION: DIRECT MIX",
   "X DISTORTION: SOLO SW",
   "X DISTORTION: SOLO LEVEL",
   "METAL DIST: TYPE",
   "METAL DIST: DIST",
   "METAL DIST: TONE",
   "METAL DIST: EFFECT LEVEL",
   "METAL DIST: BOTTOM",
   "METAL DIST: DIRECT MIX",
   "METAL DIST: SOLO SW",
   "METAL DIST: SOLO LEVEL",
   "BASS METAL DIST: DIST",
   "BASS METAL DIST: TONE",
   "BASS METAL DIST: EFFECT LEVEL",
   "BASS METAL DIST: BOTTOM",
   "BASS METAL DIST: DIRECT MIX",
   "BASS METAL DIST: SOLO SW",
   "BASS METAL DIST: SOLO LEVEL",
   "DISTORTION: TYPE",
   "DISTORTION: DIST",
   "DISTORTION: TONE",
   "DISTORTION: EFFECT LEVEL",
   "DISTORTION: BOTTOM",
   "DISTORTION: DIRECT MIX",
   "DISTORTION: SOLO SW",
   "DISTORTION: SOLO LEVEL",
   "BASS DISTORTION: TYPE",
   "BASS DISTORTION: DRIVE",
   "BASS DISTORTION: TONE",
   "BASS DISTORTION: EFFECT LEVEL",
   "BASS DISTORTION: BOTTOM",
   "BASS DISTORTION: DIRECT MIX",
   "BASS DISTORTION: SOLO SW",
   "BASS DISTORTION: SOLO LEVEL",
   "FUZZ: TYPE",
   "FUZZ: FUZZ",
   "FUZZ: TONE",
   "FUZZ: EFFECT LEVEL",
   "FUZZ: BOTTOM",
   "FUZZ: DIRECT MIX",
   "FUZZ: SOLO SW",
   "FUZZ: SOLO LEVEL",
   "BASS FUZZ: FUZZ",
   "BASS FUZZ: TONE",
   "BASS FUZZ: EFFECT LEVEL",
   "BASS FUZZ: BOTTOM",
   "BASS FUZZ: DIRECT MIX",
   "BASS FUZZ: SOLO SW",
   "BASS FUZZ: SOLO LEVEL",
   "PREAMP: TYPE",
   "PREAMP: GAIN",
   "PREAMP: LEVEL",
   "PREAMP: BASS",
   "PREAMP: MIDDLE",
   "PREAMP: TREBLE",
   "PREAMP: PRESENCE",
   "PREAMP: GAIN SW",
   "PREAMP: SOLO SW",
   "PREAMP: SOLO LEVEL",
   "PREAMP: BRIGHT SW",
   "PREAMP: SAG",
   "PREAMP: RESONANCE",
   "PREAMP: DIRECT MIX",
   "PREAMP: SP TYPE",
   "PREAMP: MIC TYPE",
   "PREAMP: MIC DISTANCE",
   "PREAMP: MIC POSITION",
   "PREAMP: MIC LEVEL",
   "BASS PREAMP: TYPE",
   "BASS PREAMP: GAIN",
   "BASS PREAMP: LEVEL",
   "BASS PREAMP: BASS",
   "BASS PREAMP: MIDDLE",
   "BASS PREAMP: TREBLE",
   "BASS PREAMP: PRESENCE",
   "BASS PREAMP: GAIN SW",
   "BASS PREAMP: SOLO SW",
   "BASS PREAMP: SOLO LEVEL",
   "BASS PREAMP: BRIGHT SW",
   "BASS PREAMP: SAG",
   "BASS PREAMP: RESONANCE",
   "BASS PREAMP: DIRECT MIX",
   "BASS PREAMP: SP TYPE",
   "BASS PREAMP: MIC TYPE",
   "BASS PREAMP: MIC DISTANCE",
   "BASS PREAMP: MIC POSITION",
   "BASS PREAMP: MIC LEVEL",
   "NOISE SUPRESS: THRESHOLD",
   "NOISE SUPRESS: RELEASE",
   "NOISE SUPRESS: DETECT",
   "DIVIDER: MODE",
   "DIVIDER: CH SELECT",
   "DIVIDER: MIX MODE",
   "DIVIDER: A:DYNAMIC",
   "DIVIDER: A:DYNAMIC SENS",
   "DIVIDER: A:FILTER",
   "DIVIDER: A:CUTOFF FREQ",
   "DIVIDER: B:DYNAMIC",
   "DIVIDER: B:DYNAMIC SENS",
   "DIVIDER: B:FILTER",
   "DIVIDER: B:CUTOFF FREQ",
   "MIXER: MODE",
   "MIXER: A LEVEL",
   "MIXER: B LEVEL",
   "MIXER: A/B BALANCE",
   "MIXER: SPREAD",
   "PARAMET EQ: LOW GAIN",
   "PARAMET EQ: HIGH GAIN",
   "PARAMET EQ: LEVEL",
   "PARAMET EQ: LOW-MID FREQ",
   "PARAMET EQ: LOW-MID Q",
   "PARAMET EQ: LOW-MID GAIN",
   "PARAMET EQ: HIGH-MID FREQ",
   "PARAMET EQ: HIGH-MID Q",
   "PARAMET EQ: HIGH-MID GAIN",
   "PARAMET EQ: LOW CUT",
   "PARAMET EQ: HIGH CUT",
   "GRAPHIC EQ: 31.5Hz",
   "GRAPHIC EQ: 63Hz",
   "GRAPHIC EQ: 125Hz",
   "GRAPHIC EQ: 250Hz",
   "GRAPHIC EQ: 500Hz",
   "GRAPHIC EQ: 1kHz",
   "GRAPHIC EQ: 2kHz",
   "GRAPHIC EQ: 4kHz",
   "GRAPHIC EQ: 8kHz",
   "GRAPHIC EQ: 16kHz",
   "GRAPHIC EQ: LEVEL",
   "CHORUS: TYPE",
   "CHORUS: DIRECT LEVEL",
   "CHORUS: RATE",
   "CHORUS: DEPTH",
   "CHORUS: EFFECT LEVEL",
   "CHORUS: LOW CUT",
   "CHORUS: HIGH CUT",
   "CHORUS: PRE-DELAY",
   "CHORUS: WAVEFORM",
   "CHORUS: 1:RATE",
   "CHORUS: 1:DEPTH",
   "CHORUS: 1:EFFECT LEVEL",
   "CHORUS: 1:PRE-DELAY",
   "CHORUS: 1:WAVEFORM",
   "CHORUS: 1:LOW CUT",
   "CHORUS: 1:HIGH CUT",
   "CHORUS: 2:RATE",
   "CHORUS: 2:DEPTH",
   "CHORUS: 2:EFFECT LEVEL",
   "CHORUS: 2:PRE-DELAY",
   "CHORUS: 2:WAVEFORM",
   "CHORUS: 2:LOW CUT",
   "CHORUS: 2:HIGH CUT",
   "CHORUS: OUTPUT MODE",
   "BASS CHORUS: TYPE",
   "BASS CHORUS: RATE",
   "BASS CHORUS: DEPTH",
   "BASS CHORUS: EFFECT LEVEL",
   "BASS CHORUS: LOW CUT",
   "BASS CHORUS: HIGH CUT",
   "BASS CHORUS: DIRECT LEVEL",
   "PRIME CHORUS: RATE",
   "PRIME CHORUS: DEPTH",
   "PRIME CHORUS: EFFECT LEVEL",
   "PRIME CHORUS: PRE-DELAY",
   "PRIME CHORUS: WAVEFORM",
   "PRIME CHORUS: LOW CUT",
   "PRIME CHORUS: HIGH CUT",
   "PRIME CHORUS: SWEETNESS",
   "PRIME CHORUS: BELL",
   "PRIME CHORUS: OUTPUT MODE",
   "OVERTONE: LOWER LEVEL",
   "OVERTONE: UPPER LEVEL",
   "OVERTONE: UNISON LEVEL",
   "OVERTONE: DIRECT LEVEL",
   "OVERTONE: DETUNE",
   "OVERTONE: OUTPUT MODE",
   "OVERTONE: LOW",
   "OVERTONE: HIGH",
   "DELAY: TIME",
   "DELAY: FEEDBACK",
   "DELAY: EFFECT LEVEL",
   "DELAY: DIRECT LEVEL",
   "DELAY: HIGH CUT",
   "DELAY: CARRYOVER",
   "DELAY PLUS: TYPE",
   "DELAY PLUS: DIRECT LEVEL",
   "DELAY PLUS: MOD RATE",
   "DELAY PLUS: MOD DEPTH",
   "DELAY PLUS: DUCK SENS",
   "DELAY PLUS: DUCK PRE DPT",
   "DELAY PLUS: DUCK POST DPT",
   "DELAY PLUS: CARRYOVER",
   "DELAY PLUS: TIME",
   "DELAY PLUS: FEEDBACK",
   "DELAY PLUS: EFFECT LEVEL",
   "DELAY PLUS: HIGH CUT",
   "DELAY PLUS: TAP TIME",
   "DELAY PLUS: AUTO TRIGGER",
   "DELAY PLUS: MODE",
   "DELAY PLUS: 1:TYPE",
   "DELAY PLUS: 1:TIME",
   "DELAY PLUS: 1:FEEDBACK",
   "DELAY PLUS: 1:EFFECT LEVEL",
   "DELAY PLUS: 1:HIGH CUT",
   "DELAY PLUS: 2:HIGH CUT",
   "DELAY PLUS: 2:TYPE",
   "DELAY PLUS: 2:TIME",
   "DELAY PLUS: 2:FEEDBACK",
   "DELAY PLUS: 2:EFFECT LEVEL",
   "ANALOG DELAY: TYPE",
   "ANALOG DELAY: TIME",
   "ANALOG DELAY: FEEDBACK",
   "ANALOG DELAY: EFFECT LEVEL",
   "ANALOG DELAY: DIRECT LEVEL",
   "ANALOG DELAY: HIGH CUT",
   "ANALOG DELAY: MOD RATE",
   "ANALOG DELAY: MOD DEPTH",
   "ANALOG DELAY: DUCK SENS",
   "ANALOG DELAY: DUCK PRE DPT",
   "ANALOG DELAY: DUCK POST DPT",
   "ANALOG DELAY: CARRYOVER",
   "SPACE ECHO: TIME",
   "SPACE ECHO: FEEDBACK",
   "SPACE ECHO: EFFECT LEVEL",
   "SPACE ECHO: DIRECT LEVEL",
   "SPACE ECHO: HIGH CUT",
   "SPACE ECHO: MOD RATE",
   "SPACE ECHO: MOD DEPTH",
   "SPACE ECHO: DUCK SENS",
   "SPACE ECHO: DUCK PRE DPT",
   "SPACE ECHO: DUCK POST DPT",
   "SPACE ECHO: HEAD",
   "SPACE ECHO: WOW FLUTTER",
   "SPACE ECHO: CARRYOVER",
   "SHIMMER DLY: TIME",
   "SHIMMER DLY: FEEDBACK",
   "SHIMMER DLY: EFFECT LEVEL",
   "SHIMMER DLY: DIRECT LEVEL",
   "SHIMMER DLY: HIGH CUT",
   "SHIMMER DLY: MOD RATE",
   "SHIMMER DLY: MOD DEPTH",
   "SHIMMER DLY: DUCK SENS",
   "SHIMMER DLY: DUCK PRE DPT",
   "SHIMMER DLY: DUCK POST DPT",
   "SHIMMER DLY: PITCH",
   "SHIMMER DLY: PITCH BALANCE",
   "SHIMMER DLY: PITCH FEEDBACK",
   "SHIMMER DLY: CARRYOVER",
   "TWIST: MODE",
   "TWIST: TRIGGER",
   "TWIST: LEVEL",
   "TWIST: RISE TIME",
   "TWIST: FALL TIME",
   "TWIST: FADE TIME",
   "TWIST: CARRYOVER",
   "WARP: TIME",
   "WARP: TRIGGER",
   "WARP: LEVEL",
   "WARP: CARRYOVER",
   "REVERB: TYPE",
   "REVERB: TIME",
   "REVERB: PRE-DELAY",
   "REVERB: EFFECT LEVEL",
   "REVERB: DENSITY",
   "REVERB: LOW CUT",
   "REVERB: HIGH CUT",
   "REVERB: DIRECT LEVEL",
   "REVERB: CARRYOVER",
   "REVERB PLUS: TYPE",
   "REVERB PLUS: TIME",
   "REVERB PLUS: TONE",
   "REVERB PLUS: EFFECT LEVEL",
   "REVERB PLUS: DENSITY",
   "REVERB PLUS: PRE-DELAY",
   "REVERB PLUS: LOW CUT",
   "REVERB PLUS: HIGH CUT",
   "REVERB PLUS: LOW DAMP",
   "REVERB PLUS: HIGH DAMP",
   "REVERB PLUS: MOD RATE",
   "REVERB PLUS: MOD DEPTH",
   "REVERB PLUS: DUCK SENS",
   "REVERB PLUS: DUCK PRE DPT",
   "REVERB PLUS: DUCK POST DPT",
   "REVERB PLUS: DIRECT LEVEL",
   "REVERB PLUS: CARRYOVER",
   "SHIMMER REV: TIME",
   "SHIMMER REV: TONE",
   "SHIMMER REV: EFFECT LEVEL",
   "SHIMMER REV: DENSITY",
   "SHIMMER REV: PRE-DELAY",
   "SHIMMER REV: LOW CUT",
   "SHIMMER REV: HIGH CUT",
   "SHIMMER REV: LOW DAMP",
   "SHIMMER REV: HIGH DAMP",
   "SHIMMER REV: MOD RATE",
   "SHIMMER REV: MOD DEPTH",
   "SHIMMER REV: DUCK SENS",
   "SHIMMER REV: DUCK PRE DPT",
   "SHIMMER REV: DUCK POST DPT",
   "SHIMMER REV: DIRECT LEVEL",
   "SHIMMER REV: 1:PITCH",
   "SHIMMER REV: 2:PITCH",
   "SHIMMER REV: 1:LEVEL",
   "SHIMMER REV: 2:LEVEL",
   "SHIMMER REV: CARRYOVER",
   "TERA ECHO: MODE",
   "TERA ECHO: SPREAD TIME",
   "TERA ECHO: FEEDBACK",
   "TERA ECHO: EFFECT LEVEL",
   "TERA ECHO: TONE",
   "TERA ECHO: DIRECT LEVEL",
   "TERA ECHO: TRIGGER",
   "TERA ECHO: CARRYOVER",
   "FLANGER: RATE",
   "FLANGER: DEPTH",
   "FLANGER: RESONANCE",
   "FLANGER: MANUAL",
   "FLANGER: STEP RATE",
   "FLANGER: LOW CUT",
   "FLANGER: EFFECT LEVEL",
   "FLANGER: DIRECT MIX",
   "BASS FLANGER: RATE",
   "BASS FLANGER: DEPTH",
   "BASS FLANGER: RESONANCE",
   "BASS FLANGER: MANUAL",
   "BASS FLANGER: STEP RATE",
   "BASS FLANGER: LOW CUT",
   "BASS FLANGER: EFFECT LEVEL",
   "BASS FLANGER: DIRECT MIX",
   "PRIME FLANGER: RATE",
   "PRIME FLANGER: DEPTH",
   "PRIME FLANGER: RESONANCE",
   "PRIME FLANGER: MANUAL",
   "PRIME FLANGER: TURBO",
   "PRIME FLANGER: WAVEFORM",
   "PRIME FLANGER: STEP RATE",
   "PRIME FLANGER: SEPARATION",
   "PRIME FLANGER: EFFECT LEVEL",
   "PRIME FLANGER: LOW DAMP",
   "PRIME FLANGER: HIGH DAMP",
   "PRIME FLANGER: DIRECT MIX",
   "PRIME FLANGER: LOW CUT",
   "PRIME FLANGER: HIGH CUT",
   "BASS PRIME FL: RATE",
   "BASS PRIME FL: DEPTH",
   "BASS PRIME FL: RESONANCE",
   "BASS PRIME FL: MANUAL",
   "BASS PRIME FL: TURBO",
   "BASS PRIME FL: WAVEFORM",
   "BASS PRIME FL: STEP RATE",
   "BASS PRIME FL: SEPARATION",
   "BASS PRIME FL: EFFECT LEVEL",
   "BASS PRIME FL: LOW DAMP",
   "BASS PRIME FL: HIGH DAMP",
   "BASS PRIME FL: DIRECT MIX",
   "BASS PRIME FL: LOW CUT",
   "BASS PRIME FL: HIGH CUT",
   "PAN: RATE",
   "PAN: DEPTH",
   "PAN: WAVEFORM",
   "PAN: EFFECT LEVEL",
   "PAN: DIRECT MIX",
   "PEDAL BEND: PITCH MIN",
   "PEDAL BEND: PITCH MAX",
   "PEDAL BEND: PEDAL POSITION",
   "PEDAL BEND: EFFECT LEVEL",
   "PEDAL BEND: DIRECT MIX",
   "BASS PEDAL BEND: PITCH MIN",
   "BASS PEDAL BEND: PITCH MAX",
   "BASS PEDAL BEND: PEDAL POSITION",
   "BASS PEDAL BEND: EFFECT LEVEL",
   "BASS PEDAL BEND: DIRECT MIX",
   "FOOT VOLUME: PEDAL POSITION",
   "FOOT VOLUME: VOLUME MIN",
   "FOOT VOLUME: VOLUME MAX",
   "FOOT VOLUME: CURVE",
   "HARMONIST: VOICE",
   "HARMONIST: 1:HARMONY",
   "HARMONIST: 1:LEVEL",
   "HARMONIST: 1:PRE-DELAY",
   "HARMONIST: 1:FEEDBACK",
   "HARMONIST: 2:HARMONY",
   "HARMONIST: 2:LEVEL",
   "HARMONIST: 2:PRE-DELAY",
   "HARMONIST: DIRECT LEVEL",
   "HARMONIST: 1:C",
   "HARMONIST: 1:Db",
   "HARMONIST: 1:D",
   "HARMONIST: 1:Eb",
   "HARMONIST: 1:E",
   "HARMONIST: 1:F",
   "HARMONIST: 1:F#",
   "HARMONIST: 1:G",
   "HARMONIST: 1:Ab",
   "HARMONIST: 1:A",
   "HARMONIST: 1:Bb",
   "HARMONIST: 1:B",
   "HARMONIST: 2:C",
   "HARMONIST: 2:Db",
   "HARMONIST: 2:D",
   "HARMONIST: 2:Eb",
   "HARMONIST: 2:E",
   "HARMONIST: 2:F",
   "HARMONIST: 2:F#",
   "HARMONIST: 2:G",
   "HARMONIST: 2:Ab",
   "HARMONIST: 2:A",
   "HARMONIST: 2:Bb",
   "HARMONIST: 2:B",
   "BASS HARMONIST: VOICE",
   "BASS HARMONIST: 1:HARMONY",
   "BASS HARMONIST: 1:LEVEL",
   "BASS HARMONIST: 1:PRE-DELAY",
   "BASS HARMONIST: 1:FEEDBACK",
   "BASS HARMONIST: 2:HARMONY",
   "BASS HARMONIST: 2:LEVEL",
   "BASS HARMONIST: 2:PRE-DELAY",
   "BASS HARMONIST: DIRECT LEVEL",
   "BASS HARMONIST: 1:C",
   "BASS HARMONIST: 1:Db",
   "BASS HARMONIST: 1:D",
   "BASS HARMONIST: 1:Eb",
   "BASS HARMONIST: 1:E",
   "BASS HARMONIST: 1:F",
   "BASS HARMONIST: 1:F#",
   "BASS HARMONIST: 1:G",
   "BASS HARMONIST: 1:Ab",
   "BASS HARMONIST: 1:A",
   "BASS HARMONIST: 1:Bb",
   "BASS HARMONIST: 1:B",
   "BASS HARMONIST: 2:C",
   "BASS HARMONIST: 2:Db",
   "BASS HARMONIST: 2:D",
   "BASS HARMONIST: 2:Eb",
   "BASS HARMONIST: 2:E",
   "BASS HARMONIST: 2:F",
   "BASS HARMONIST: 2:F#",
   "BASS HARMONIST: 2:G",
   "BASS HARMONIST: 2:Ab",
   "BASS HARMONIST: 2:A",
   "BASS HARMONIST: 2:Bb",
   "BASS HARMONIST: 2:B",
   "OCTAVE: -2 OCT",
   "OCTAVE: -1 OCT",
   "OCTAVE: DIRECT LEVEL",
   "POLY OCTAVE: RANGE",
   "POLY OCTAVE: OCTAVE LEVEL",
   "POLY OCTAVE: DIRECT LEVEL",
   "BASS OCTAVE: -2 OCT",
   "BASS OCTAVE: -1 OCT",
   "BASS OCTAVE: DIRECT LEVEL",
   "CLASSIC VIBE: MODE",
   "CLASSIC VIBE: RATE",
   "CLASSIC VIBE: DEPTH",
   "CLASSIC VIBE: EFFECT LEVEL",
   "PHASER: STAGE",
   "PHASER: RATE",
   "PHASER: DEPTH",
   "PHASER: RESONANCE",
   "PHASER: MANUAL",
   "PHASER: STEP RATE",
   "PHASER: EFFECT LEVEL",
   "PHASER: DIRECT MIX",
   "BASS PHASER: STAGE",
   "BASS PHASER: RATE",
   "BASS PHASER: DEPTH",
   "BASS PHASER: RESONANCE",
   "BASS PHASER: MANUAL",
   "BASS PHASER: STEP RATE",
   "BASS PHASER: EFFECT LEVEL",
   "BASS PHASER: DIRECT MIX",
   "PRIME PHASER: STAGE",
   "PRIME PHASER: RATE",
   "PRIME PHASER: DEPTH",
   "PRIME PHASER: RESONANCE",
   "PRIME PHASER: MANUAL",
   "PRIME PHASER: WAVEFORM",
   "PRIME PHASER: STEP RATE",
   "PRIME PHASER: BI-PHASE",
   "PRIME PHASER: SEPARATION",
   "PRIME PHASER: LOW DAMP",
   "PRIME PHASER: HIGH DAMP",
   "PRIME PHASER: LOW CUT",
   "PRIME PHASER: HIGH CUT",
   "PRIME PHASER: EFFECT LEVEL",
   "PRIME PHASER: DIRECT MIX",
   "BASS PRIME PH: STAGE",
   "BASS PRIME PH: RATE",
   "BASS PRIME PH: DEPTH",
   "BASS PRIME PH: RESONANCE",
   "BASS PRIME PH: MANUAL",
   "BASS PRIME PH: WAVEFORM",
   "BASS PRIME PH: STEP RATE",
   "BASS PRIME PH: BI-PHASE",
   "BASS PRIME PH: SEPARATION",
   "BASS PRIME PH: LOW DAMP",
   "BASS PRIME PH: HIGH DAMP",
   "BASS PRIME PH: LOW CUT",
   "BASS PRIME PH: HIGH CUT",
   "BASS PRIME PH: EFFECT LEVEL",
   "BASS PRIME PH: DIRECT MIX",
   "SCRIPT PH: RATE",
   "SCRIPT PH: DEPTH",
   "SCRIPT PH: EFFECT LEVEL",
   "SCRIPT PH: DIRECT MIX",
   "PITCH SHIFTER: VOICE",
   "PITCH SHIFTER: DIRECT LEVEL",
   "PITCH SHIFTER: 1:PITCH",
   "PITCH SHIFTER: 1:MODE",
   "PITCH SHIFTER: 1:FINE",
   "PITCH SHIFTER: 1:PRE-DELAY",
   "PITCH SHIFTER: 1:LEVEL",
   "PITCH SHIFTER: 1:FEEDBACK",
   "PITCH SHIFTER: 2:PITCH",
   "PITCH SHIFTER: 2:MODE",
   "PITCH SHIFTER: 2:FINE",
   "PITCH SHIFTER: 2:PRE-DELAY",
   "PITCH SHIFTER: 2:LEVEL",
   "BASS PITCH SHIFT: VOICE",
   "BASS PITCH SHIFT: DIRECT LEVEL",
   "BASS PITCH SHIFT: 1:PITCH",
   "BASS PITCH SHIFT: 1:MODE",
   "BASS PITCH SHIFT: 1:FINE",
   "BASS PITCH SHIFT: 1:PRE-DELAY",
   "BASS PITCH SHIFT: 1:LEVEL",
   "BASS PITCH SHIFT: 1:FEEDBACK",
   "BASS PITCH SHIFT: 2:PITCH",
   "BASS PITCH SHIFT: 2:MODE",
   "BASS PITCH SHIFT: 2:FINE",
   "BASS PITCH SHIFT: 2:PRE-DELAY",
   "BASS PITCH SHIFT: 2:LEVEL",
   "RING MOD: INTELLIGENT",
   "RING MOD: FREQUENCY",
   "RING MOD: MOD RATE",
   "RING MOD: MOD DEPTH",
   "RING MOD: EFFECT LEVEL",
   "RING MOD: DIRECT MIX",
   "ROTARY: SPEED SELECT",
   "ROTARY: SLOW RATE",
   "ROTARY: FAST RATE",
   "ROTARY: EFFECT LEVEL",
   "ROTARY: RISE TIME",
   "ROTARY: FALL TIME",
   "ROTARY: MIC DISTANCE",
   "ROTARY: ROTOR/HORN",
   "ROTARY: DRIVE",
   "ROTARY: DIRECT MIX",
   "TREMOLO: RATE",
   "TREMOLO: DEPTH",
   "TREMOLO: WAVEFORM",
   "TREMOLO: EFFECT LEVEL",
   "TREMOLO: TRIGGER",
   "TREMOLO: RISE TIME",
   "TREMOLO: DIRECT MIX",
   "VIBRATO: RATE",
   "VIBRATO: DEPTH",
   "VIBRATO: TRIGGER",
   "VIBRATO: RISE TIME",
   "VIBRATO: EFFECT LEVEL",
   "PRIME VIB: RATE",
   "PRIME VIB: DEPTH",
   "PRIME VIB: COLOR",
   "PRIME VIB: EFFECT LEVEL",
   "PRIME VIB: TRIGGER",
   "PRIME VIB: RISE TIME",
   "PRIME VIB: DIRECT MIX",
   "S-BEND: TRIGGER",
   "S-BEND: PITCH",
   "S-BEND: RISE TIME",
   "S-BEND: FALL TIME",
   "BASS S-BEND: TRIGGER",
   "BASS S-BEND: PITCH",
   "BASS S-BEND: RISE TIME",
   "BASS S-BEND: FALL TIME",
   "PHRASE LOOP: LOOP LEVEL",
   "SEND/RETURN: MODE",
   "SEND/RETURN: SEND LEVEL",
   "SEND/RETURN: RET LEVEL",
   "SEND/RETURN: ADJUST",
   "SEND/RETURN: INVERT",
   "MASTER: MEMORY LEVEL",
   "MASTER: BPM",
   "MASTER: KEY",
   "MASTER: INPUT SETTING",
   "MASTER: AMP CTL1",
   "MASTER: AMP CTL2",
   "TUNER: ON/OFF",
   "N/A: N/A",
   "N/A: N/A",
   "SLICER: PATTERN",
   "SLICER: RATE",
   "SLICER: TRIGGER",
   "SLICER: EFFECT LEVEL",
   "SLICER: ATTACK",
   "SLICER: DUTY",
   "SLICER: DIRECT MIX",
   "HUMANIZER: MODE",
   "HUMANIZER: VOWEL1",
   "HUMANIZER: VOWEL2",
   "HUMANIZER: SENS",
   "HUMANIZER: RATE",
   "HUMANIZER: DEPTH",
   "HUMANIZER: MANUAL",
   "HUMANIZER: LEVEL",
   "FEEDBACKER: MODE",
   "FEEDBACKER: TRIGGER",
   "FEEDBACKER: DEPTH",
   "FEEDBACKER: RISE TIME",
   "FEEDBACKER: OCT RISE TIME",
   "FEEDBACKER: FEEDBACK",
   "FEEDBACKER: OCT FEEDBACK",
   "FEEDBACKER: VIB RATE",
   "FEEDBACKER: VIB DEPTH",
   "SITAR SIM: SENS",
   "SITAR SIM: DEPTH",
   "SITAR SIM: TONE",
   "SITAR SIM: EFFECT LEVEL",
   "SITAR SIM: RESONANCE",
   "SITAR SIM: BUZZ",
   "SITAR SIM: DIRECT MIX",
   "AUTO WAH: FILTER MODE",
   "AUTO WAH: RATE",
   "AUTO WAH: DEPTH",
   "AUTO WAH: EFFECT LEVEL",
   "AUTO WAH: FREQUENCY",
   "AUTO WAH: RESONANCE",
   "AUTO WAH: WAVEFORM",
   "AUTO WAH: DIRECT MIX"
  ]
 },
 "knobs": [
  {
   "rotulo": "Knob 1",
   "fxItem": 105,
   "alvo": 109
  },
  {
   "rotulo": "Knob 2",
   "fxItem": 106,
   "alvo": 113
  },
  {
   "rotulo": "Knob 3",
   "fxItem": 107,
   "alvo": 117
  },
  {
   "rotulo": "Knob 4",
   "fxItem": 108,
   "alvo": 121
  }
 ],
 "memoryMidi": [
  {
   "rotulo": "MIDI 1",
   "campos": [
    {
     "chave": "ch",
     "rotulo": "Channel",
     "desloc": 53,
     "tipo": "byte",
     "lista": [
      "OFF",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16"
     ]
    },
    {
     "chave": "bankMsb",
     "rotulo": "Bank MSB",
     "desloc": 54,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "bankLsb",
     "rotulo": "Bank LSB",
     "desloc": 56,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "pc",
     "rotulo": "PC#",
     "desloc": 58,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc1",
     "rotulo": "CC1#",
     "desloc": 60,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc1Val",
     "rotulo": "CC1 value",
     "desloc": 62,
     "tipo": "byte",
     "min": 0,
     "max": 127
    },
    {
     "chave": "cc2",
     "rotulo": "CC2#",
     "desloc": 63,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc2Val",
     "rotulo": "CC2 value",
     "desloc": 65,
     "tipo": "byte",
     "min": 0,
     "max": 127
    }
   ]
  },
  {
   "rotulo": "MIDI 2",
   "campos": [
    {
     "chave": "ch",
     "rotulo": "Channel",
     "desloc": 66,
     "tipo": "byte",
     "lista": [
      "OFF",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16"
     ]
    },
    {
     "chave": "bankMsb",
     "rotulo": "Bank MSB",
     "desloc": 67,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "bankLsb",
     "rotulo": "Bank LSB",
     "desloc": 69,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "pc",
     "rotulo": "PC#",
     "desloc": 71,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc1",
     "rotulo": "CC1#",
     "desloc": 73,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc1Val",
     "rotulo": "CC1 value",
     "desloc": 75,
     "tipo": "byte",
     "min": 0,
     "max": 127
    },
    {
     "chave": "cc2",
     "rotulo": "CC2#",
     "desloc": 76,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc2Val",
     "rotulo": "CC2 value",
     "desloc": 78,
     "tipo": "byte",
     "min": 0,
     "max": 127
    }
   ]
  },
  {
   "rotulo": "MIDI 3",
   "campos": [
    {
     "chave": "ch",
     "rotulo": "Channel",
     "desloc": 79,
     "tipo": "byte",
     "lista": [
      "OFF",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16"
     ]
    },
    {
     "chave": "bankMsb",
     "rotulo": "Bank MSB",
     "desloc": 80,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "bankLsb",
     "rotulo": "Bank LSB",
     "desloc": 82,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "pc",
     "rotulo": "PC#",
     "desloc": 84,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc1",
     "rotulo": "CC1#",
     "desloc": 86,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc1Val",
     "rotulo": "CC1 value",
     "desloc": 88,
     "tipo": "byte",
     "min": 0,
     "max": 127
    },
    {
     "chave": "cc2",
     "rotulo": "CC2#",
     "desloc": 89,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc2Val",
     "rotulo": "CC2 value",
     "desloc": 91,
     "tipo": "byte",
     "min": 0,
     "max": 127
    }
   ]
  },
  {
   "rotulo": "MIDI 4",
   "campos": [
    {
     "chave": "ch",
     "rotulo": "Channel",
     "desloc": 92,
     "tipo": "byte",
     "lista": [
      "OFF",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16"
     ]
    },
    {
     "chave": "bankMsb",
     "rotulo": "Bank MSB",
     "desloc": 93,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "bankLsb",
     "rotulo": "Bank LSB",
     "desloc": 95,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "pc",
     "rotulo": "PC#",
     "desloc": 97,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc1",
     "rotulo": "CC1#",
     "desloc": 99,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc1Val",
     "rotulo": "CC1 value",
     "desloc": 101,
     "tipo": "byte",
     "min": 0,
     "max": 127
    },
    {
     "chave": "cc2",
     "rotulo": "CC2#",
     "desloc": 102,
     "tipo": "nibbles2",
     "min": 0,
     "max": 128,
     "zeroOff": true
    },
    {
     "chave": "cc2Val",
     "rotulo": "CC2 value",
     "desloc": 104,
     "tipo": "byte",
     "min": 0,
     "max": 127
    }
   ]
  }
 ],
 "presetsFabrica": [
  "GX DUAL DRIVE",
  "HEAVY METAL",
  "STUDIO BLUES",
  "JC CLEAN",
  "LEAD DRIVE",
  "CRUNCH LEAD",
  "NEO SOUL",
  "MODERN OD",
  "MODERN DS",
  "CLEAN+SHIMMER",
  "MILD DRIVE",
  "ACOUSTIC GUITAR",
  "X-ULTRA FEED",
  "X-OPTIMA SD-1",
  "X-TITAN MDP",
  "DUAL X LEAD",
  "SLICER DRIVE",
  "HUMANIZER AC",
  "BRIGHT SITAR",
  "AUTO WAH BOX",
  "FUZZY ROCK",
  "PHASER CLEAN",
  "BG DRIVE",
  "OCTAVE CLEAN",
  "HI-GAIN LEAD",
  "DIMENSION FL",
  "DRIVE + OCT CLN",
  "SYNTH LEAD",
  "RICH CHORUS DS",
  "BASIC GIG",
  "ROTARY+ECHO",
  "AMBIENT CLEAN",
  "FUSION SOLO",
  "TWEED DRIVE",
  "FLYING OVERTONE",
  "CONSOLE CLEAN",
  "DUAL CRUNCH",
  "FUZZ SOLO",
  "BOOST BAR BROS",
  "THE BELLS",
  "WINDWARD",
  "ANCIENT MOON",
  "CAPO'S & NUTS",
  "WINTER IN 2047",
  "JAZZ CLUB",
  "GITARRE SPIELEN",
  "SLOW DANCE",
  "OVERTONE ORGAN",
  "NEW AGED BLUES",
  "SPACE ECHO",
  "CLEAR DRIVE",
  "GOOD FEELING",
  "SURF COWBOY",
  "AMERICANA",
  "TREBLE BOOST",
  "DIGITAL OCEAN",
  "FUNK DRIVE",
  "SUPER CLEAN/DS",
  "ANCIENT DREAM",
  "OCTAVE FUNK",
  "GRAVITY GAINS",
  "AMBIENT LEAD",
  "DJENT METAL",
  "SKYBLUE PINK",
  "FUZZY DIST",
  "DIMI GILMORIX",
  "A LIGHTER TOUCH",
  "HARMONIC DIST",
  "PROUD DAD",
  "DRY CRUNCH",
  "OCTAVE CRUNCH",
  "FUSION SWELLS",
  "LO-FI CLEAN",
  "SLAP GUITAR",
  "1993",
  "OCTAVE ORGAN",
  "BIG DRIVE",
  "BLUE LAKE",
  "FAIRY OF FOREST",
  "HARMONIC DRIVE",
  "PROG LEAD TONE",
  "CRYSTAL CLEAN",
  "CLEAN BOOSTER",
  "BUBBLE DELAY",
  "HOT COUNTRY",
  "EXPENSIVE TASTE",
  "SWAMP CHORUS",
  "EVERY 00'S MOVIE",
  "STUDIO BASS",
  "ROCK BASS CRUNCH",
  "CLEAN ROCK BASS",
  "T WAH BASS",
  "DIST ROCK BASS",
  "MONO BASS CLOUD",
  "SYNTHY OCT BASS",
  "FUZZ BASS",
  "LOOPER CLEAN",
  "LOOPER CRUNCH",
  "LOOPER DRIVE"
 ]
};
